apiVersion: v1
kind: Service

metadata:
  name: tamp-education-service
  namespace: tamp-education

spec:
  type: NodePort

  selector:
    app: tamp-education

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30081
